<?php

namespace app\widgets;


class GridView extends \kartik\grid\GridView
{

//    public $options;

    public function init()
    {
        $this->options = [
            'style' => 'font-size:12px;'
        ];
        return parent::init(); // TODO: Change the autogenerated stub
    }
}
